server:
  servlet:
    encoding:
      mapping:
        utf-8: UTF-8
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb3
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sistematurnosgrupo12@gmail.com
    password: pmoc lfcl rjij rkvu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
logging:
    level:
      org:
        hibernate:
            springframework:
                security: DEBUG
                SQL: DEBUG
                type:
                  descriptor:
                        sql:
                            BasicBinder: TRACE


